name: "Build IG Publisher and cache JAR"
description: "Builds the IG publisher from a particular GitHub ref (branch name, tag, or commit hash)"
inputs:
  ref:
    description: "The GitHub ref to build the IG publisher from"
    required: false
    default: "master"
  core-ref:
    description: "An optional ref to build the core library from"
    required: false

runs:
  using: "composite"

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - name: Checkout Core Project
      if: inputs.core-ref != ''
      uses: actions/checkout@v4
      with:
        repository: hapifhir/org.hl7.fhir.core
        ref: ${{ inputs.core-ref }}
        path: ${{ github.workspace }}/core-build
    - name: Build Core Project
      if: inputs.core-ref != ''
      run: mvn clean install -Dmaven.test.skip=true
      shell: bash
      working-directory: ${{ github.workspace }}/core-build
    - name: Checkout IG Publisher Project
      uses: actions/checkout@v4
      with:
        repository: HL7/fhir-ig-publisher
        ref: ${{ inputs.ref }}
        path: ${{ github.workspace }}/ig-publisher-cli-build
    - name: Build IG Publisher
      run: mvn clean install -Dmaven.test.skip=true
      shell: bash
      working-directory: ${{ github.workspace }}/ig-publisher-cli-build
    - name: Delete sources jar
      run: rm ${{ github.workspace }}/ig-publisher-cli-build/org.hl7.fhir.publisher.cli/target/org.hl7.fhir.publisher.cli-**-sources.jar
      shell: bash
    - name: Delete javadoc jar
      run: rm ${{ github.workspace }}/ig-publisher-cli-build/org.hl7.fhir.publisher.cli/target/org.hl7.fhir.publisher.cli-**-javadoc.jar
      shell: bash
    - name: Move JAR to project root
      run: mv ${{ github.workspace }}/ig-publisher-cli-build/org.hl7.fhir.publisher.cli/target/org.hl7.fhir.publisher.cli-**.jar ig-publisher.jar
      shell: bash
    - name: Cache Publisher JAR
      id: cache-publisher-jar
      uses: actions/cache@v4
      with:
        path: ig-publisher.jar
        key: ig-publisher-${{ inputs.ref }}-${{ github.run_id }}
