jobs:
  - ${{ each execTest in parameters.execTests }}:
      - job: ${{execTest.igName}}_${{value}}

        displayName: Test publisher.jar exec on ${{execTest.igName}} ${{execTest.vmImage}}
        
        pool:
          vmImage: ${{execTest.vmImage}}

        variables:
          currentImage: ${{execTest.vmImage}}
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execTest.javaToolOptions}}

        steps:
          - template: ./.azure/qa-diff/pipelines/build-and-exec-steps-template.yml
            parameters:
                igName: ${{execTest.igName}}
                gitRepo: ${{execTest.gitRepo}}
                gitCommitHash: ${{execTest.gitCommitHash}}
                jdkVersion: ${{execTest.jdkVersion}}
                javaToolOptions: ${{execTest.javaToolOptions}}
                publishQAArtifacts: true

  - job: publish_qa_diff
    dependsOn:
      - ${{ each execTest in parameters.execTests }}:
          - ubuntu_java_11_${{ module }}
