jobs:
  - ${{ each execQaJob in parameters.execQaJobs }}:
      - job: ${{ replace(execQaJob.igName,'.', '_')}}_qa

        displayName: Run publisher.jar exec on ${{execQaJob.igName}} and publish QA results
        
        pool:
          vmImage: ${{execQaJob.vmImage}}

        variables:
          currentImage: ${{execQaJob.vmImage}}
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execQaJob.javaToolOptions}}

        steps:
          - template: ./.azure/qa-diff/pipelines/build-and-exec-steps-template.yml
            parameters:
                igName: ${{execQaJob.igName}}
                gitRepo: ${{execQaJob.gitRepo}}
                gitCommitHash: ${{execQaJob.gitCommitHash}}
                jdkVersion: ${{execQaJob.jdkVersion}}
                javaToolOptions: ${{execQaJob.javaToolOptions}}
                publishQAArtifacts: true

  - job: publish_qa_diff
    displayName: 'Generate diff zip'
    dependsOn:
      - ${{ each execQaJob in parameters.execQaJobs }}:
          - ${{ replace(execQaJob.igName,'.', '_')}}_qa
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          itemPattern: '**/*.qa'
          targetPath: '$(Pipeline.Workspace)/qaDiff/actual'
      - script: mkdir $(Pipeline.Workspace)/qaDiff/expected
      - script: cp ./.azure/qa-diff/expected/* $(Pipeline.Workspace)/qaDiff/expected
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/qaDiff'
          artifact: qa-diff
        displayName: 'Publish QA diff artifact'
