jobs:
  - ${{ each execTest in parameters.execTests }}:
      - job:

        displayName: Test publisher.jar exec on ${{execTest.igName}} ${{execTest.vmImage}}
        
        pool:
          vmImage: ${{execTest.vmImage}}


        variables:
          currentImage: ${{execTest.vmImage}}
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execTest.javaToolOptions}}

        steps:

          - task: UseRubyVersion@0
            inputs:
              versionSpec: '>= 3.3'

          - script : |
              ridk enable
              ridk install 3
            condition: eq( variables['Agent.OS'], 'Windows_NT' )
            displayName: 'ridk to install devkit'

          - script: |
              gem install bundler
              bundle init
              bundle update --bundler
              bundle install --retry=3 --jobs=4
              gem install jekyll
            displayName: 'jekyll install'

          - script: |
              npm install -g fsh-sushi
            displayName: 'fsh-sushi install'

          # Runs 'mvn install'
          - task: Maven@4
            displayName: 'Build project'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              options: '-DskipTests'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{execTest.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'install'

          - task: Bash@3
            displayName: 'Clone target IG'
            inputs:
              targetType: 'inline'
              script: mkdir -p $(Pipeline.Workspace)/target-ig; git clone ${{execTest.gitRepo}} "$(Pipeline.Workspace)/target-ig"

          - task: Maven@4
            displayName: 'Run IG Publisher with IG'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{execTest.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              options: '-pl org.hl7.fhir.publisher.cli -Dpublisher.cli.exec.target-ig="$(Pipeline.Workspace)/target-ig"'
              publishJUnitResults: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'org.codehaus.mojo:exec-maven-plugin:exec@target-ig-cli'