jobs:
  - ${{ each execTest in parameters.execTests }}:
      - job:

        displayName: ${{execTest.displayName}}
        
        pool:
          vmImage: ${{execTest.vmImage}}


        variables:
          currentImage: ${{execTest.vmImage}}
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execTest.javaToolOptions}}

        steps:
          - checkout: self
          - checkout: IgRepo
          # Runs 'mvn clean package'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{execTest.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{execTest.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              options: '-pl org.hl7.fhir.publisher.cli'
              publishJUnitResults: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'exec:exec'