trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: "nightly-xig-build-process"
  branches:
    include: 
    - master
  always: true # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.

pool:
  vmImage: ubuntu-latest

variables:
- group: XIG_VARIABLE_GROUP

jobs:
- job: build_and_copy_xig
  timeoutInMinutes: 70
  steps:
  - task: Bash@3
    displayName: 'Download publisher'
    inputs:
      targetType: 'inline'
      script: 'wget https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar'

  - task: Bash@3
    displayName: 'Make output database'
    inputs:
      targetType: 'inline'
      script: 'touch xig.db'

  - task: Bash@3
    displayName: 'Make cache dir'
    inputs:
      targetType: 'inline'
      script: 'mkdir xig-cache'

  - task: Bash@3
    displayName: 'Run publisher with xig param'
    inputs:
      targetType: 'inline'
      script: 'java -Xmx7168m -jar ./publisher.jar -xig xig.db -xig-cache xig-cache'

#  - task: Bash@3
#    displayName: 'Make dummy file'
#    inputs:
#      targetType: 'inline'
#      script: |
#        echo 'Why hello there' > xig_output/hello.txt

  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'xig.private.key' 

  # This step includes chmod to the private key to avoid ssh complaining about permissions.
  - task: Bash@3
    displayName: 'Clean previous results'
    retryCountOnTaskFailure: 5
    inputs:
      targetType: 'inline'
      script: |
        chmod 400 $(Agent.TempDirectory)/xig.private.key
        ssh -o "StrictHostKeyChecking=no" -i $(Agent.TempDirectory)/xig.private.key $(XIG_USER)@$(XIG_SERVER) 'if [ -d "$(XIG_TARGET_DIRECTORY)" ]; then find $(XIG_TARGET_DIRECTORY) -name "*" -delete; fi && mkdir $(XIG_TARGET_DIRECTORY)'

  - task: Bash@3
    displayName: 'Tar results'
    enabled: false
    inputs:
      targetType: 'inline'
      script: |
        tar -C ./xig_output -zcvf xig-www.tar.gz .

  - task: Bash@3
    displayName: 'Copy tar'
    enabled: false
    retryCountOnTaskFailure: 5
    inputs:
      targetType: 'inline'
      script: |
        scp -o "StrictHostKeyChecking=no" -i $(Agent.TempDirectory)/xig.private.key xig-www.tar.gz $(XIG_USER)@$(XIG_SERVER):$(XIG_TARGET_DIRECTORY)/

  - task: Bash@3
    displayName: 'Decompress tar'
    enabled: false
    retryCountOnTaskFailure: 5
    inputs:
      targetType: 'inline'
      script: |
        ssh -o "StrictHostKeyChecking=no" -i $(Agent.TempDirectory)/xig.private.key $(XIG_USER)@$(XIG_SERVER) 'tar -zxvf $(XIG_TARGET_DIRECTORY)/xig-www.tar.gz -C $(XIG_TARGET_DIRECTORY)'
