# We only want to trigger a test build on PRs to the main branch.
trigger: none

pr:
  - master
  - release

# Different users have different machine setups, we run the build three times, on ubuntu, osx, and windows.
# Azure doesn't always have the same Java versions on each system, so they are enumerated for each system independently.
jobs:
  - template: ./.azure/templates/build-and-test-jobs-template.yml
  - template: ./.azure/templates/build-and-exec-qa-jobs-template.yml
  - template: ./.azure/templates/build-and-exec-jobs-template.yml

