# We only want to trigger a test build on PRs to the main branch.
trigger: none

pr:
  - master
  - release

# Different users have different machine setups, we run the build three times, on ubuntu, osx, and windows.
# Azure doesn't always have the same Java versions on each system, so they are enumerated for each system independently.
jobs:
  - template: build-and-test-jobs-template.yml
    parameters:
      images:
        # This image is here so that at least one job specifically sets Cp1252 file encodings, which are normally set by the JDK (which Azure can change on each latest image)
        - displayName: ubuntu-latest-java-17-cp1252
          vmImage: ubuntu-latest
          jdkVersion: 1.17
          javaToolOptions: -Dfile.encoding=Cp1252
        - displayName: ubuntu-latest-java-17
          vmImage: ubuntu-latest
          jdkVersion: 1.17
          javaToolOptions:
        - displayName: macos-latest-java-17
          vmImage: macos-latest
          jdkVersion: 1.17
          javaToolOptions:
        - displayName: windows-latest-java-17
          vmImage: windows-latest
          jdkVersion: 1.17
          javaToolOptions:
  - template: build-and-exec-jobs-template.yml
    parameters:
      execTests:
        - igName: fhir-tools-ig-exec
          vmImage: ubuntu-latest
          jdkVersion: 1.17
          gitRepo: https://github.com/FHIR/fhir-tools-ig.git
        - igName: fhir-tools-ig-exec
          vmImage: ubuntu-latest
          jdkVersion: 1.21
          gitRepo: https://github.com/FHIR/fhir-tools-ig.git
        #- igName: fhir-tools-ig-exec
        #  vmImage: windows-latest
        #  jdkVersion: 1.17
        #  gitRepo: https://github.com/FHIR/fhir-tools-ig.git
        # - igName: fhir-tools-ig-exec
        #  vmImage: windows-latest
        #  jdkVersion: 1.21
        #  gitRepo: https://github.com/FHIR/fhir-tools-ig.git
        - igName: fhir-tools-ig-exec
          vmImage: macos-latest
          jdkVersion: 1.17
          gitRepo: https://github.com/FHIR/fhir-tools-ig.git
        - igName: ACME-FSH-IG-Example
          vmImage: ubuntu-latest
          jdkVersion: 1.17
          gitRepo: https://github.com/FirelyTeam/ACME-FSH-IG-Example.git
        # - igName: ACME-FSH-IG-Example
        #  vmImage: windows-latest
        #  jdkVersion: 1.17
        #  gitRepo: https://github.com/FirelyTeam/ACME-FSH-IG-Example.git
        - igName: ACME-FSH-IG-Example
          vmImage: macos-latest
          jdkVersion: 1.17
          gitRepo: https://github.com/FirelyTeam/ACME-FSH-IG-Example.git
