# We only want to trigger a test build on PRs to the main branch.
trigger: none

pr:
  - master
  - release

# Different users have different machine setups, we run the build three times, on ubuntu, osx, and windows.
# Azure doesn't always have the same Java versions on each system, so they are enumerated for each system independently.
jobs:
  - template: build-and-test-jobs-template.yml
    parameters:
      images:
        # This image is here so that at least one job specifically sets Cp1252 file encodings, which are normally set by the JDK (which Azure can change on each latest image)
        - displayName: ubuntu-latest-java-17-cp1252
          vmImage: ubuntu-latest
          jdkVersion: 1.11
          javaToolOptions: -Dfile.encoding=Cp1252
        - displayName: ubuntu-latest-java-11
          vmImage: ubuntu-latest
          jdkVersion: 1.11
          javaToolOptions:
        - displayName: macos-latest-java-11
          vmImage: macos-latest
          jdkVersion: 1.11
          javaToolOptions:
        - displayName: windows-latest-java-11
          vmImage: windows-latest
          jdkVersion: 1.11
          javaToolOptions:
  - template: build-and-exec-qa-jobs-template.yml
    parameters:
      execTests:
        - igName: example.fhir.uv.myig
          vmImage: ubuntu-latest
          jdkVersion: 1.11
          gitRepo: https://github.com/FHIR/sample-ig.git
          gitCommitHash: 3167a0b
        - igName: fhir.base.template.ig
          vmImage: ubuntu-latest
          jdkVersion: 1.11
          gitRepo: https://github.com/HL7/ig-template-base.git
          gitCommitHash: cc52687

