package org.hl7.fhir.igtools.web;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

import org.hl7.fhir.utilities.FileUtilities;
import org.hl7.fhir.utilities.Utilities;
import org.hl7.fhir.utilities.json.model.JsonArray;
import org.hl7.fhir.utilities.json.model.JsonObject;
import org.hl7.fhir.utilities.json.parser.JsonParser;

/**
 * Support files for the opt-in dynamic publish box (publish-setup.json website.dynamic-publish-box).
 *
 * Two files live at each IG root, next to package-list.json, and are (re)written whenever
 * package-list.json is written - they belong to the same mutable zone as history.html and the feeds:
 *
 * <ul>
 * <li><b>package-list.js</b> - the content of package-list.json wrapped in a script-loadable
 *   variable assignment. Pages reference it with a relative script tag, so unlike a fetch of
 *   package-list.json it works from file:// and under any base path (previews, mirrors), and
 *   under a strict CSP (same-origin script, no inline code).</li>
 * <li><b>publish-box.js</b> - the client logic (shipped as a resource in the publisher jar)
 *   that corrects the publish box statement on pages of past versions once a newer version
 *   has been published. Because it is served from the mutable IG root, fixes to it reach
 *   the pages of past versions without rewriting them.</li>
 * </ul>
 *
 * Each published version folder also gets a <b>publish-box-pages.json</b> manifest (written once,
 * when that version is published) listing the version's HTML pages, so that later publications can
 * existence-check cross-version page links without needing the version's full file tree locally.
 */
public class DynamicPublishBoxSupport {

  public static final String PACKAGE_LIST_JS = "package-list.js";
  public static final String PUBLISH_BOX_JS = "publish-box.js";
  public static final String PAGES_MANIFEST = "publish-box-pages.json";

  /**
   * Write package-list.js + publish-box.js to the IG root folder. Call whenever
   * package-list.json in that folder has been created or updated.
   */
  public static void writeSupportFiles(String igRootFolder) throws IOException {
    String json = FileUtilities.fileToString(Utilities.path(igRootFolder, "package-list.json"));
    StringBuilder b = new StringBuilder();
    b.append("// Generated by the FHIR IG publisher alongside package-list.json. Do not edit.\n");
    b.append("var fhirPackageList = ");
    // "</" must not appear inside a script element (it would close it); JSON allows the escape
    b.append(json.replace("</", "<\\/"));
    b.append(";\n");
    writeIfChanged(b.toString(), Utilities.path(igRootFolder, PACKAGE_LIST_JS));

    try (InputStream is = DynamicPublishBoxSupport.class.getResourceAsStream("/web/publish-box.js")) {
      if (is == null) {
        throw new IOException("Unable to find /web/publish-box.js on the classpath");
      }
      writeIfChanged(FileUtilities.streamToString(is), Utilities.path(igRootFolder, PUBLISH_BOX_JS));
    }
  }

  /** avoids churning file timestamps (and so uploads/syncs) on re-runs that change nothing */
  private static void writeIfChanged(String content, String path) throws IOException {
    File f = new File(path);
    if (f.exists() && content.equals(FileUtilities.fileToString(f))) {
      return;
    }
    FileUtilities.stringToFile(content, path);
  }

  /**
   * Write the page manifest for a published version folder: the sorted list of the folder's
   * HTML pages, relative to the folder. Written when the version is published (and during
   * migration by -publish-update); read by {@link IGReleaseVersionUpdater} in later publications
   * so the "Page versions:" links can be existence-checked without the version's file tree.
   */
  public static void writePagesManifest(String versionFolder) throws IOException {
    List<String> pages = new ArrayList<>();
    listHtmlFiles(new File(versionFolder), "", pages);
    Collections.sort(pages);
    JsonObject json = new JsonObject();
    json.add("about", "Page inventory for the dynamic publish box. Generated by the FHIR IG publisher when this version was published. Do not edit.");
    JsonArray arr = new JsonArray();
    for (String p : pages) {
      arr.add(p);
    }
    json.add("pages", arr);
    writeIfChanged(JsonParser.compose(json, true), Utilities.path(versionFolder, PAGES_MANIFEST));
  }

  /**
   * Load a version folder's page manifest into the given set (url-style relative paths).
   * Returns false (set untouched) if the folder has no manifest.
   */
  public static boolean loadPagesManifest(String versionFolder, Set<String> pages) throws IOException {
    File f = new File(Utilities.path(versionFolder, PAGES_MANIFEST));
    if (!f.exists()) {
      return false;
    }
    JsonObject json = JsonParser.parseObjectFromFile(f.getAbsolutePath());
    pages.addAll(json.getStrings("pages"));
    return true;
  }

  private static void listHtmlFiles(File dir, String prefix, List<String> pages) {
    File[] files = dir.listFiles();
    if (files == null) {
      return;
    }
    for (File f : files) {
      if (f.isDirectory()) {
        listHtmlFiles(f, prefix + f.getName() + "/", pages);
      } else if (f.getName().endsWith(".html") || f.getName().endsWith(".htm")) {
        pages.add(prefix + f.getName());
      }
    }
  }
}
