parameters:
  images:
    # This image is here so that at least one job specifically sets Cp1252 file encodings, which are normally set by the JDK (which Azure can change on each latest image)
    - displayName: ubuntu-latest-java-17-cp1252
      vmImage: ubuntu-latest
      jdkVersion: 1.11
      javaToolOptions: -Dfile.encoding=Cp1252
    - displayName: ubuntu-latest-java-11
      vmImage: ubuntu-latest
      jdkVersion: 1.11
      javaToolOptions:
    - displayName: macos-latest-java-11
      vmImage: macos-latest
      jdkVersion: 1.11
      javaToolOptions:
    - displayName: windows-latest-java-11
      vmImage: windows-latest
      jdkVersion: 1.11
      javaToolOptions:

jobs:
  - ${{ each image in parameters.images }}:
      - job:

        displayName: ${{image.displayName}}
        
        pool:
          vmImage: ${{image.vmImage}}
        
        variables:
          currentImage: ${{image.vmImage}}
          VERSION:
          JAVA_TOOL_OPTIONS: ${{image.javaToolOptions}}

        steps:
          # Runs 'mvn install'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{image.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'install'

          # Runs 'mvn exec to test that cli runs'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{image.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              options: '-pl org.hl7.fhir.publisher.cli'
              publishJUnitResults: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'exec:exec'