parameters:
  execQaJobs:
    - igName: hl7.fhir.us.core
      gitRepo: https://github.com/HL7/US-Core-R4.git
      gitCommitHash: 20378a9
    - igName: hl7.fhir.us.ecr
      gitRepo: https://github.com/HL7/case-reporting.git
      gitCommitHash: c808159
    - igName: hl7.fhir.uv.ips
      gitRepo: https://github.com/HL7/fhir-ips.git
      gitCommitHash: 5c71808
    - igName: hl7.fhir.uv.sdc
      gitRepo: https://github.com/HL7/sdc.git
      gitCommitHash: 9ce7886
    - igName: ihe.mhd.fhir
      gitRepo: https://github.com/IHE/ITI.MHD.git
      gitCommitHash: 052c8c3
    - igName: fhir.base.template.ig
      gitRepo: https://github.com/HL7/ig-template-base.git
      gitCommitHash: e346855
    - igName: hl7.base.template.ig
      gitRepo: https://github.com/HL7/ig-template-hl7.git
      gitCommitHash: 48ded21
    - igName: hl7.fhir.au.base
      gitRepo: https://github.com/hl7au/au-fhir-base.git
      gitCommitHash: 75a1c27
    - igName: hl7.fhir.template.ig
      gitRepo: https://github.com/HL7/ig-template-fhir.git
      gitCommitHash: eb0e010
    - igName: hl7.fhir.uv.howto
      gitRepo: https://github.com/FHIR/ig-guidance.git
      gitCommitHash: 2d39f83
    - igName: example.fhir.uv.myig
      gitRepo: https://github.com/FHIR/sample-ig
      gitCommitHash: b2f6f9f
    - igName: hl7.fhir.uv.tools
      gitRepo: https://github.com/FHIR/fhir-tools-ig
      gitCommitHash: 9f5d35e
    - igName: hl7.fhir.uv.extensions
      gitRepo: https://github.com/HL7/fhir-extensions
      gitCommitHash: d2c9e88
    - igName: hl7.cda.uv.core
      gitRepo: https://github.com/HL7/CDA-core-sd
      gitCommitHash: 801f4a0

jobs:
  - ${{ each execQaJob in parameters.execQaJobs }}:
      - job: ${{ replace(execQaJob.igName,'.', '_')}}_qa

        displayName: Run publisher on ${{execQaJob.igName}} and publish QA results
        
        pool:
          vmImage: macos-latest

        variables:
          currentImage: macos-latest
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execQaJob.javaToolOptions}}

        steps:
          - template: ./build-and-exec-steps-template.yml
            parameters:
                igName: ${{execQaJob.igName}}
                gitRepo: ${{execQaJob.gitRepo}}
                gitCommitHash: ${{execQaJob.gitCommitHash}}
                vmImage: macos-latest
                jdkVersion: 1.11
                javaToolOptions: ${{execQaJob.javaToolOptions}}
                publishQAArtifacts: true

  - job: publish_qa_diff
    displayName: 'Generate diff zip'
    dependsOn:
      - ${{ each execQaJob in parameters.execQaJobs }}:
          - ${{ replace(execQaJob.igName,'.', '_')}}_qa
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          targetPath: '$(Pipeline.Workspace)/qaDiffTemp'
      - script: mkdir -p $(Pipeline.Workspace)/qaDiff/actual
      - script: cp $(Pipeline.Workspace)/qaDiffTemp/**/* $(Pipeline.Workspace)/qaDiff/actual
      - script: mkdir $(Pipeline.Workspace)/qaDiff/expected
      - script: cp ./.azure/qa-diff/expected/* $(Pipeline.Workspace)/qaDiff/expected
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/qaDiff'
          artifact: qa-diff
        displayName: 'Publish QA diff artifact'
