jobs:
  - ${{ each execJob in parameters.execJobs }}:
      - job:

        displayName: Run publisher on ${{execJob.igName}} on ${{execJob.vmImage}} and ${{execJob.jdkVersion}}
        
        pool:
          vmImage: ${{execJob.vmImage}}

        variables:
          currentImage: ${{execJob.vmImage}}
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execJob.javaToolOptions}}

        steps:
          - template: ./build-and-exec-steps-template.yml
            parameters:
                igName: ${{execJob.igName}}
                gitRepo: ${{execJob.gitRepo}}
                jdkVersion: ${{execJob.jdkVersion}}
                javaToolOptions: ${{execJob.javaToolOptions}}