parameters:
  execQaJobs:
    - igName: hl7.fhir.us.core
      gitRepo: https://github.com/HL7/US-Core-R4.git
      gitCommitHash: bd7c8062c
    - igName: hl7.fhir.us.ecr
      gitRepo: https://github.com/HL7/case-reporting.git
      gitCommitHash: 4885e855
    - igName: hl7.fhir.uv.ips
      gitRepo: https://github.com/HL7/fhir-ips.git
      gitCommitHash: 94140e15
    - igName: hl7.fhir.uv.sdc
      gitRepo: https://github.com/HL7/sdc.git
      gitCommitHash: 0ae731b
    - igName: ihe.mhd.fhir
      gitRepo: https://github.com/IHE/ITI.MHD
      gitCommitHash: fe4bd96

jobs:
  - ${{ each execQaJob in parameters.execQaJobs }}:
      - job: ${{ replace(execQaJob.igName,'.', '_')}}_qa

        displayName: Run publisher on ${{execQaJob.igName}} and publish QA results
        
        pool:
          vmImage: ubuntu-latest

        variables:
          currentImage: ubuntu-latest
          VERSION:
          JAVA_TOOL_OPTIONS: ${{execQaJob.javaToolOptions}}

        steps:
          - template: ./build-and-exec-steps-template.yml
            parameters:
                igName: ${{execQaJob.igName}}
                gitRepo: ${{execQaJob.gitRepo}}
                gitCommitHash: ${{execQaJob.gitCommitHash}}
                jdkVersion: 1.11
                javaToolOptions: ${{execQaJob.javaToolOptions}}
                publishQAArtifacts: true

  - job: publish_qa_diff
    displayName: 'Generate diff zip'
    dependsOn:
      - ${{ each execQaJob in parameters.execQaJobs }}:
          - ${{ replace(execQaJob.igName,'.', '_')}}_qa
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          targetPath: '$(Pipeline.Workspace)/qaDiffTemp'
      - script: mkdir -p $(Pipeline.Workspace)/qaDiff/actual
      - script: cp $(Pipeline.Workspace)/qaDiffTemp/**/* $(Pipeline.Workspace)/qaDiff/actual
      - script: mkdir $(Pipeline.Workspace)/qaDiff/expected
      - script: cp ./.azure/qa-diff/expected/* $(Pipeline.Workspace)/qaDiff/expected
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/qaDiff'
          artifact: qa-diff
        displayName: 'Publish QA diff artifact'
