name: "Publish IG and cache QA"
description: "Publishes an IG from a GitHub repo using a cached IG publisher JAR and uploads the QA artifact"
inputs:
  ref:
    description: "The GitHub ref for the IG publisher JAR"
    required: false
    default: "master"
  ig:
    description: "The IG. This can be a local directory rooted in the current repository, or a GitHub repository."
    required: true
  source-type:
    type: choice
    description: "The type of source for the IG. This can "
    options:
      - local
      - github
    default: github
  memory:
    description: "The Java Memory (-Xmx) for running the IG Publisher"
    required: false
    default: "10G"

runs:
  using: "composite"

  steps:
    - name: set repo key
      # This is a hacky way to generate a repo key without '/' characters, so an artifact
      # key can be generated.
      run: |
        ENV_REPO_KEY=${{ inputs.ig }}
        echo "REPO_KEY=${ENV_REPO_KEY//\//_}" >> $GITHUB_ENV
      shell: bash
    - name: Get Job ID from GH API
      id: get-job-id
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          JOBS=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          JOB_ID=$(echo $JOBS | jq -r '.JOBS[] | select(.runner_name=="${{ runner.name }}") | .id')
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV
      shell: bash
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: install jekyll
      run: |
        gem install jekyll bundler
      shell: bash
    - name: install sushi
      run: |
        npm install -g fsh-sushi
      shell: bash

    # If this is a GitHub repo, set the target directory to /ig and checkout the repo there.
    - name: set target directory
      if: inputs.source-type == 'github'
      run: |
        echo "TARGET_DIRECTORY=${{ github.workspace }}/ig" >> $GITHUB_ENV
      shell: bash
    - name: Checkout IG from a GitHub repo
      if: inputs.source-type == 'github'
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.ig }}
        path: ${{ env.TARGET_DIRECTORY }}

    # If this is a local repo, set the target directory to its location in the root of this workspace and do a sparse
    # checkout of its contents.
    - name: set target directory
      if: inputs.source-type == 'local'
      run: |
        echo "TARGET_DIRECTORY=${{ github.workspace }}/${{ inputs.ig }}" >> $GITHUB_ENV
      shell: bash
    # Sparse checkout the IG from this repo and checkout the contents of the .github directory so workflows can be
    # completed
    - name: Sparse Checkout IG from this repo
      if: inputs.source-type == 'local'
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          ${{ inputs.ig }}
    - name: Publisher JAR from cache
      id: publisher-jar-from-cache
      uses: actions/cache@v4
      with:
        path: ig-publisher.jar
        key: ig-publisher-${{ inputs.ref }}-${{ github.run_id }}
    - name: Run Publisher
      id: run-publisher
      run: java -Xmx${{ inputs.memory }} -jar ig-publisher.jar -ig ${{ env.TARGET_DIRECTORY }}
      shell: bash
      continue-on-error: true
    - name: Generate empty QA on failure
      if: steps.run-publisher.outcome != 'success'
      run: |
        mkdir -p ${{ env.TARGET_DIRECTORY }}/output
        echo "IG Publish step failed. Check outputs in https://github.com/HL7/fhir-ig-publisher/actions/runs/${{ github.run_id }}/job/${{ env.JOB_ID }} for ${{ inputs.ig }}" > ${{ env.TARGET_DIRECTORY }}/output/qa.compare.txt
        echo "::warning::IG Publish step failed."
      shell: bash
    - name: Move QA to project root
      run: mv ${{ env.TARGET_DIRECTORY }}/output/qa.compare.txt ${{ github.workspace }}/qa.compare.${{ inputs.ref }}.txt
      shell: bash
    - name: Cache QA compare
      uses: actions/cache@v4
      with:
        key: ${{ env.REPO_KEY }}-${{ inputs.ref }}-${{github.run_id}}
        path: ${{ github.workspace }}/qa.compare.${{ inputs.ref }}.txt