name: BIDI CHECK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bidi_checker_job:
    runs-on: ubuntu-latest
    name: Check for bidi unicode characters in repo
    steps:
      # Checkout the repo code. IMPORTANT, this step is needed to populate the directory defined by GITHUB_WORKSPACE
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        id: checkout
      # Run the check for bidi characters.
      - name: Check for bidi characters
        id: bidi_check
        uses: HL7/bidi-checker-action@02112ffc62b81938f58a5dd7c69ef537e3a4b999 # v1.9
        env:
          IGNORE: \.png$
      - name: Get the output time
        run: echo "The time was ${{ steps.bidi_check.outputs.time }}"
