on:
  pull_request:
    branches:
      - master

jobs:
  build_from_branch:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        repository: HL7/fhir-ig-publisher
        ref: ${{ github.sha }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true
    - name: Cache Publisher JAR
      id: cache-primes
      uses: actions/cache@v4
      with:
        path: org.hl7.fhir.publisher.cli/target/org.hl7.fhir.publisher.cli-**-SNAPSHOT.jar
        key: ig-publisher-branch
        
