on:
  pull_request:
    branches:
      - master

jobs:
  load-ig-repositories:
    name: Load IG repositories
    runs-on: ubuntu-latest
    outputs:
      ig-repositories-json: ${{ steps.load-ig-repositories-json.outputs.json }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         sparse-checkout: |
          .github
      - name: Load IG repositories JSON
        id: load-ig-repositories-json
        run: |
          content=`cat ./.github/workflows/ig-repositories.json`
          echo "test=${content}" >> "$GITHUB_OUTPUT"
        shell: bash

  build-ig-publisher-jars:
    name: Build IG Publisher JARs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ref: [master, "${{ github.sha }}" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Build and Cache IG Publisher
        uses: ./.github/actions/build-and-cache-ig-publisher
        with:
          ref: ${{ matrix.ref }}

  generate-qa-artifacts:  
    name: Generate QA artifacts
    needs: [load-ig-repositories, build-ig-publisher-jars]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ref: [master, "${{ github.sha }}" ]
        repo: [ HL7/ig-template-base, FHIR/ig-guidance ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
    - name: test-output
      run: |
        echo "test-output"
        echo "${{ needs.load-ig-repositories.outputs.ig-repositories-json }}"
        shell: bash
    - name: Publish IG and create QA artifact
      uses: ./.github/actions/publish-ig-and-upload-qa-artifact
      with:
        ref: ${{ matrix.ref }}
        repo: ${{ matrix.repo }}

  diff-generated-qa-artifacts:  
    name: Diff generated QA artifacts
    needs: generate-qa-artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ HL7/ig-template-base, FHIR/ig-guidance ]
      fail-fast: false
    steps:
    - name: set repo key
      # This is a hacky way to generate a repo key without '/' characters, so an artifact 
      # key can be generated.
      run: |
          ENV_REPO_KEY=${{matrix.repo}}
          echo "REPO_KEY=${ENV_REPO_KEY//\//_}" >> $GITHUB_ENV
    - name : Download branch QA artifact
      uses: actions/download-artifact@v4
      with:
        name: qa-${{env.REPO_KEY}}-${{ github.sha }}
        path: qa.compare.branch.txt
    - name : Download master QA artifact
      uses: actions/download-artifact@v4
      with:
        name: qa-${{env.REPO_KEY}}-master
        path: qa.compare.master.txt
    - name: Diff QA artifacts
      run: |
        diff -bur qa.compare.master.txt qa.compare.branch.txt
    
    
