on:
  pull_request:
    branches:
      - master

jobs:
  build_project:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        repository: https://github.com/HL7/fhir-ig-publisher
        ref: ${{ github.sha }}
        
        
